### ISSUE TITLE
long term consistency of the repo directory / file structure

### ISSUE THREAD

**Issue by dunkeki** [oasis-open/cti-stix-common-objects#45]
We (and I hope others) have built STIX/TAXII capabilities that leverage this repo - thanks!  Those tools navigate the directory / file structure to retrieve STIX objects, JSON schema, etc.  As such, they have embedded knowledge (as little as possible) as to that structure.  Changes to the directory / file tree would break the tools.  This issue requests that the directory / file structure remain as is - consistent - for the long term.  Changes would need to be publicly announced, proposed to both the STIX and TAXII TCs, and approved per the chair's chosen method.

**Comment by ejratl** [comment]
@dunkeki Thanks for reporting this issue! We currently have no plans to change the directory structure. I will add a note to the README for any possible future maintainers, so that they are aware of the issue as well, so that any future change will be discourage, or, if it cannot be avoided, announced well in advance to ensure that tool developers have a change to adapt early. Really appreciate the heads up from an implementer!
